import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import type { ReportContent } from "@/lib/supabase/types";
import type { ReportTemplate } from "@/lib/report-template";

// ---------------------------------------------------------------------------
// Font registration — URL-based for Vercel Serverless compatibility
// ---------------------------------------------------------------------------

const fontUrl =
  (process.env.NEXT_PUBLIC_APP_URL ?? "https://nipoai.app") +
  "/fonts/NotoSansJP-Variable.ttf";

Font.register({
  family: "NotoSansJP",
  src: fontUrl,
});

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface ReportPdfProps {
  content: ReportContent;
  template: ReportTemplate;
  userName: string;
  reportDate: string;
  workspaceName: string;
  showWatermark: boolean;
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  page: {
    fontFamily: "NotoSansJP",
    paddingTop: 48,
    paddingBottom: 48,
    paddingHorizontal: 48,
    fontSize: 10,
    color: "#1a1a1a",
    backgroundColor: "#ffffff",
  },
  header: {
    marginBottom: 24,
    borderBottomWidth: 2,
    borderBottomColor: "#2563eb",
    paddingBottom: 16,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 10,
    color: "#6b7280",
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#2563eb",
    marginBottom: 6,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  item: {
    fontSize: 10,
    color: "#374151",
    marginBottom: 3,
    paddingLeft: 12,
  },
  bullet: {
    color: "#6b7280",
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    textAlign: "center",
    fontSize: 8,
    color: "#9ca3af",
  },
  watermark: {
    position: "absolute",
    top: "45%",
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 32,
    color: "#e5e7eb",
    opacity: 0.5,
    transform: "rotate(-30deg)",
  },
});

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function ReportPdfDocument({
  content,
  template,
  userName,
  reportDate,
  workspaceName,
  showWatermark,
}: ReportPdfProps) {
  return (
    <Document
      title={`${userName}の日報_${reportDate}`}
      author="NipoAI"
    >
      <Page size="A4" style={styles.page}>
        {/* Watermark */}
        {showWatermark && (
          <Text style={styles.watermark}>
            Generated by NipoAI — Free Plan
          </Text>
        )}

        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>
            {userName}さんの日報
          </Text>
          <Text style={styles.subtitle}>
            {reportDate}  |  {workspaceName}
          </Text>
        </View>

        {/* Sections */}
        {template.map((section) => {
          const items = content[section.key] ?? [];
          if (items.length === 0) return null;

          return (
            <View key={section.key} style={styles.section}>
              <Text style={styles.sectionTitle}>{section.label}</Text>
              {items.map((item, idx) => (
                <Text key={idx} style={styles.item}>
                  <Text style={styles.bullet}>•  </Text>
                  {item}
                </Text>
              ))}
            </View>
          );
        })}

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by NipoAI
        </Text>
      </Page>
    </Document>
  );
}
